ludo/urls.py
"""ludo URL Configuration."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
 + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLS."""

# Django
from django.urls import path

# Views
from posts import views


urlpatterns = [

    path(
        route='', 
        view=views.list_posts, 
        name='list_posts'
    ),

    path(
        route='detail/<int:pk>',
        view=views.detail_post,
        name='detail'
    )

]

posts/models.py
"""Post models."""

# Django
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    """Post model."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to='posts/photos')

    content = models.TextField()
    url_reference = models.URLField()

    labels = models.CharField(max_length=500)
    order = models.IntegerField(null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return title and username."""

        return '{} by @{}'.format(self.title, self.user.username)



class Comment(models.Model):
    """Comment model."""

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    profile = models.ForeignKey('users.Profile', on_delete=models.CASCADE, null=True, blank=True)
    is_approved = models.BooleanField(default=True)

    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text
    

users/models.py
"""User models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with 
    otheer information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    
    picture = models.ImageField(upload_to='users/pictures', 
        blank=True, 
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""

        return self.user.username

posts/forms.py
# Django
from django import forms

# models 
from posts.models import Post, Comment


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('text',)

posts/views.py
"""Posts views."""

# Django
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.core.paginator import Paginator

# Model 
from posts.models import Post

# Forms
from posts.forms import CommentForm


def list_posts(request):
    """List existing posts."""

    query = request.GET.get('q')
    paginate_by = 6

    if query:
        posts = Post.objects.filter(
            Q(title__icontains=query) |
            Q(labels__icontains=query) 
        ).distinct()
    else:
        posts = Post.objects.all().order_by('-created')

    paginator = Paginator(posts, paginate_by)

    page_number = request.GET.get('page')
    page_objects = paginator.get_page(page_number)

    return render(request, 'posts/list_posts.html', {'page_objects': page_objects})


def detail_post(request, pk):
    """Detail Post."""

    post = Post.objects.get(pk=pk)

    comment_form = CommentForm(request.POST or None)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.save()
        comment_form = CommentForm()
        
    return render(
        request, 
        'posts/detail_post.html', 
        {
            'post': post,
            'form': comment_form
        }
    )

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %} {% endblock head_content %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body>
    {% include "nav.html" %}
    
    <div class="container main">
        {% block container %}
        {% endblock container %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:list_posts'%}">
                    <img src="{% static "img/logo_ludo.png" %}" height="75" class="d-inline-block align-top"/>
                </a>
            </ul>

            <form method="GET" class="form-inline">
                <input 
                    class="form-control mr-sm-2" 
                    name="q"
                    value="{{ request.GET.q }}"
                    type="search" 
                    placeholder="Buscar" 
                    aria-label="Search"
                >
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
            </form>

        </div>
    </div>
</nav>

templates/posts/add_comment.html
{% block content %}
    <h1>Nuevo comentario</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Enviar</button>
    </form>
{% endblock %}

templates/posts/detail_post.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Ludo Posts</title>
{% endblock head_content %}


{% block container %}
    <div class="container">
        <div class="row">
            <div class="col">
            <h2 class="ml-1 mt-1">{{ post.title }}</h2>
            </div>
        </div>
        <div class="row">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="{{ post.url_reference }}" allowfullscreen></iframe>
            </div>
        </div>
        <div class="row">          
            <div class="col">
                <p class="text-justify">
                    {{ post.content|linebreaksbr }}
                </p>
            <div>
        <div>
        <div class="row">
            <div class="col">
                <h6 class="mr-3 mt-1 text-right">@{{ post.user.username }}</h6>
            </div>
        </div>
        <hr>
        
        <h6>Nuevo comentario</h6>
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Enviar</button>
        </form>

        <hr>
        {% for comment in post.comments.all %}
            <div class="comment">
                <p>{{ comment.text|linebreaks }}</p>
                <div class="date">{{ comment.created }}</div>
                <strong>{% if comment.profile %}{{ comment.profile }}{% else %}Anónimo{% endif %}</strong>
            </div>
        {% empty %}
            <p> Sin comentarios </p>
        {% endfor %}
    </div>
{% endblock container %}

templates/posts/list_posts.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Ludo Posts</title>
{% endblock head_content %}

{% block container %}

    <div class="content-img">
        {% load static %}
        <img src="{% static "img/img_main.jpg" %}" class="card-img-top image" alt="Ludo"></img>
        <button type="button" class="btn btn-info btn-abs" data-toggle="modal" data-target="#moreInfo">Más información</button>
    </div>

    <!-- Modal -->
    <div id="moreInfo" class="modal fade" role="dialog">
        <div class="modal-dialog">

        <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Información</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <p>Información a detalle.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container list_posts">
        <div class="row">
            {% for post in page_objects %}
                <div class="col text-center mt-3">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ post.photo.url }}" class="card-img-top image" alt="{{ post.title }}">
                        <div class="card-body" >
                            <h5 class="card-title">{{ post.title }}</h5>
                            <h6 class="mr-3 mt-1">{{ post.labels }}</h6>
                            <h6 class="mr-3 mt-1">@{{ post.user.username }}</h6>
                            <a href="{% url 'posts:detail' pk=post.pk %}" class="btn btn-primary">
                                Más detalles
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>



    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if page_objects.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                        &laquo;
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_objects.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                        anterior
                    </a>
                </li>
            {% endif %}

            <li class="page-item current">
                <a class="page-link">Page {{ page_objects.number }} of {{ page_objects.paginator.num_pages }}</a>
            </li>

            {% if page_objects.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_objects.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                        siguiente
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_objects.paginator.num_pages }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">
                         &raquo;
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>

    
{% endblock container %}

templates/users/base.html
<!DOCTYPE html>
<htmllang="en">
<head>
    <metacharset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <linkrel="stylesheet"href="{% static 'css/main.css' %}">
    <linkrel="stylesheet"href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"crossorigin="anonymous" />
    <linkrel="stylesheet"href="{% static 'css/main.css' %}" />
</head>
<bodyclass="h-100">
    <divclass="container h-100">
        <divclass="row h-100 justify-content-center align-items-center">
            <divclass="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5"id="auth-container">
                <imgsrc="{% static "img/instagram.png" %}"class="img-fluid rounded mx-auto d-block pb-4"style="max-width: 60%;">

                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>